// @ts-check
/**
 * Published ARP lat/lng from `docs/data/airfields.json` for Playwright fixtures.
 * **Generated by** `node scripts/sync-airfield-test-arps.js` — re-run after
 * airfield chart position changes.
 */
const data = require('../docs/data/airfields.json');

/** @param {string} code */
function arp(code) {
  const a = data.airfields.find(x => x.name === code);
  if (!a) throw new Error('docs/data/airfields.json missing airfield ' + code);
  return { lat: a.lat, lng: a.lng, name: code };
}

const LLHZ = arp('LLHZ');
const LLHA = arp('LLHA');
const LLBG = arp('LLBG');

/** @returns {{ lat: number, lng: number, name: string }[]} */
function pairLLHZ_LLHA() {
  return [
    { lat: LLHZ.lat, lng: LLHZ.lng, name: 'LLHZ' },
    { lat: LLHA.lat, lng: LLHA.lng, name: 'LLHA' },
  ];
}

module.exports = { arp, LLHZ, LLHA, LLBG, pairLLHZ_LLHA };
