// @ts-check
// One mark, drawn everywhere the app is installed from: the favicon, the two PWA icons, the
// Android launcher (square, round and adaptive) and the splash screen. They are generated by
// scripts/make-icons.mjs from a single description, and these guard what a hand edit or a
// half-finished run would break -- a blank tile on someone's home screen.
const { test, expect } = require('./_setup');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const RES = path.join(ROOT, 'mobile/android/app/src/main/res');
const dataUri = (p) =>
  'data:image/png;base64,' + fs.readFileSync(path.join(ROOT, p)).toString('base64');

// Decoding happens in the browser we already have open -- no image library to install. Returns
// the size, the fraction of pixels that differ from the image's own top-left pixel (a blank
// tile scores 0), and how many of those lie outside the middle 80% circle a maskable icon may
// be cropped to.
async function measure(page, file) {
  return page.evaluate(async (src) => {
    const img = new Image();
    img.src = src;
    await img.decode();
    const c = document.createElement('canvas');
    c.width = img.naturalWidth; c.height = img.naturalHeight;
    c.getContext('2d').drawImage(img, 0, 0);
    const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data;
    const at = (i) => `${d[i]},${d[i + 1]},${d[i + 2]},${d[i + 3]}`;
    const bg = at(0);
    let ink = 0, outside = 0, blue = 0;
    const r = c.width * 0.4;
    for (let y = 0; y < c.height; y++) {
      for (let x = 0; x < c.width; x++) {
        const i = (y * c.width + x) * 4;
        if (at(i) === bg) continue;
        ink++;
        if (d[i + 2] > d[i] + 20 && d[i + 2] > d[i + 1] + 20) blue++;
        if (Math.hypot(x - c.width / 2, y - c.height / 2) > r) outside++;
      }
    }
    return {
      w: c.width, h: c.height, ink: ink / (c.width * c.height),
      blue: blue / (c.width * c.height), outside,
    };
  }, dataUri(file));
}

test('the favicon draws the leg, the fix it left and the aircraft', () => {
  const svg = fs.readFileSync(path.join(ROOT, 'docs/favicon.svg'), 'utf8');
  expect(svg).toContain('stroke-dasharray');          // the leg flown so far
  expect(svg).toMatch(/<circle[^>]*r="4"/);           // the departure fix
  expect(svg).toContain('rotate(58)');                // the aircraft, flying it
  expect(svg).toContain('#231F20');                   // on NavAid's own ground
});

test('the PWA icons are the declared sizes and are not blank', async ({ page }) => {
  for (const [file, size] of [['docs/assets/icon-192.png', 192], ['docs/assets/icon-512.png', 512]]) {
    const m = await measure(page, file);
    expect({ file, w: m.w, h: m.h }).toEqual({ file, w: size, h: size });
    expect(m.ink).toBeGreaterThan(0.02);
  }
});

test('the iOS icon uses the current route-trail mark', async ({ page }) => {
  const file = 'mobile/ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png';
  const m = await measure(page, file);
  const generator = fs.readFileSync(path.join(ROOT, 'scripts/make-icons.mjs'), 'utf8');

  expect({ w: m.w, h: m.h }).toEqual({ w: 1024, h: 1024 });
  expect(m.ink).toBeGreaterThan(0.02);
  expect(m.blue).toBeGreaterThan(0.005);
  expect(generator).toContain('AppIcon.appiconset');
});

// Declared "any maskable" in the manifest, so a launcher may crop them to a circle: the mark
// has to sit inside it. Anything outside the safe circle would be shaved off.
test('the maskable icons keep the mark inside the safe circle', async ({ page }) => {
  expect((await measure(page, 'docs/assets/icon-512.png')).outside).toBe(0);
  expect((await measure(page, 'docs/assets/icon-192.png')).outside).toBe(0);
});

test('every launcher density is present, square and drawn', async ({ page }) => {
  const sizes = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
  for (const [density, size] of Object.entries(sizes)) {
    for (const name of ['ic_launcher', 'ic_launcher_round', 'ic_launcher_foreground']) {
      const file = path.relative(ROOT, path.join(RES, `mipmap-${density}/${name}.png`));
      const m = await measure(page, file);
      expect({ file, w: m.w, h: m.h }).toEqual({ file, w: size, h: size });
      expect(m.ink).toBeGreaterThan(0.01);
    }
  }
});

test('the splash screens keep the size each density expects', async ({ page }) => {
  const expected = {
    'drawable': [480, 320],
    'drawable-land-mdpi': [480, 320], 'drawable-port-mdpi': [320, 480],
    'drawable-land-hdpi': [800, 480], 'drawable-port-hdpi': [480, 800],
    'drawable-land-xhdpi': [1280, 720], 'drawable-port-xhdpi': [720, 1280],
    'drawable-land-xxhdpi': [1600, 960], 'drawable-port-xxhdpi': [960, 1600],
    'drawable-land-xxxhdpi': [1920, 1280], 'drawable-port-xxxhdpi': [1280, 1920],
  };
  for (const [dir, [w, h]] of Object.entries(expected)) {
    const file = path.relative(ROOT, path.join(RES, `${dir}/splash.png`));
    const m = await measure(page, file);
    expect({ file, w: m.w, h: m.h }).toEqual({ file, w, h });
    expect(m.ink).toBeGreaterThan(0.005);
  }
});
